# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('legs', models.IntegerField()),
                ('birthday', models.DateTimeField()),
                ('is_bird', models.BooleanField()),
            ],
        ),
    ]
