# Generated by Django 2.1.1 on 2018-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_filterdsl_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='favorite_food',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
