# Generated by Django 2.1.7 on 2019-03-08 19:48

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_filterdsl_tests', '0002_animalmodel_favorite_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='feeding_time',
            field=models.TimeField(default=django.utils.datetime_safe.time),
            preserve_default=False,
        ),
    ]
