# Generated by Django 2.1.7 on 2019-03-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_filterdsl_tests', '0003_animalmodel_feeding_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='keeper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kept_animals', to='rest_framework_filterdsl_tests.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_animals', to='rest_framework_filterdsl_tests.Person'),
            preserve_default=False,
        ),
    ]
